name = "cr-agent-worker"
main = ".mastra/output/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]


[vars]
OPENAI_API_KEY = ""
CLOUDFLARE_API_TOKEN=""